var OWS = {
  name: 'OWS',
  defaultElementNamespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1',
  defaultAttributeNamespaceURI: 'http:\/\/www.w3.org\/1999\/xlink',
  typeInfos: [{
      type: 'classInfo',
      localName: 'AcceptVersionsType',
      propertyInfos: [{
          type: 'element',
          name: 'version',
          collection: true,
          elementName: 'Version',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'CodeType',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'codeSpace',
          typeInfo: 'String',
          attributeName: {
            localPart: 'codeSpace'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'DatasetDescriptionSummaryBaseType',
      baseTypeInfo: 'OWS.DescriptionType',
      propertyInfos: [{
          type: 'element',
          name: 'wgs84BoundingBox',
          collection: true,
          elementName: 'WGS84BoundingBox',
          typeInfo: 'OWS.WGS84BoundingBoxType'
        }, {
          type: 'element',
          name: 'identifier',
          elementName: 'Identifier',
          typeInfo: 'OWS.CodeType'
        }, {
          name: 'boundingBox',
          collection: true,
          elementName: 'BoundingBox',
          typeInfo: 'OWS.BoundingBoxType',
          type: 'elementRef'
        }, {
          type: 'element',
          name: 'metadata',
          collection: true,
          elementName: 'Metadata',
          typeInfo: 'OWS.MetadataType'
        }, {
          type: 'element',
          name: 'datasetDescriptionSummary',
          collection: true,
          elementName: 'DatasetDescriptionSummary',
          typeInfo: 'OWS.DatasetDescriptionSummaryBaseType'
        }]
    }, {
      type: 'classInfo',
      localName: 'Operation',
      propertyInfos: [{
          type: 'element',
          name: 'dcp',
          collection: true,
          elementName: 'DCP',
          typeInfo: 'OWS.DCP'
        }, {
          type: 'element',
          name: 'parameter',
          collection: true,
          elementName: 'Parameter',
          typeInfo: 'OWS.DomainType'
        }, {
          type: 'element',
          name: 'constraint',
          collection: true,
          elementName: 'Constraint',
          typeInfo: 'OWS.DomainType'
        }, {
          type: 'element',
          name: 'metadata',
          collection: true,
          elementName: 'Metadata',
          typeInfo: 'OWS.MetadataType'
        }, {
          name: 'name',
          typeInfo: 'String',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'DCP',
      propertyInfos: [{
          type: 'element',
          name: 'http',
          elementName: 'HTTP',
          typeInfo: 'OWS.HTTP'
        }]
    }, {
      type: 'classInfo',
      localName: 'HTTP',
      propertyInfos: [{
          name: 'getOrPost',
          collection: true,
          elementTypeInfos: [{
              elementName: 'Post',
              typeInfo: 'OWS.RequestMethodType'
            }, {
              elementName: 'Get',
              typeInfo: 'OWS.RequestMethodType'
            }],
          type: 'elementRefs'
        }]
    }, {
      type: 'classInfo',
      localName: 'RequestMethodType',
      baseTypeInfo: 'OWS.OnlineResourceType',
      propertyInfos: [{
          type: 'element',
          name: 'constraint',
          collection: true,
          elementName: 'Constraint',
          typeInfo: 'OWS.DomainType'
        }]
    }, {
      type: 'classInfo',
      localName: 'DomainType',
      baseTypeInfo: 'OWS.UnNamedDomainType',
      propertyInfos: [{
          name: 'name',
          typeInfo: 'String',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'MetadataType',
      propertyInfos: [{
          type: 'element',
          name: 'abstractMetaData',
          elementName: 'AbstractMetaData',
          typeInfo: 'AnyType'
        }, {
          name: 'about',
          typeInfo: 'String',
          attributeName: {
            localPart: 'about'
          },
          type: 'attribute'
        }, {
          name: 'type',
          typeInfo: 'String',
          attributeName: 'type',
          type: 'attribute'
        }, {
          name: 'href',
          typeInfo: 'String',
          attributeName: 'href',
          type: 'attribute'
        }, {
          name: 'role',
          typeInfo: 'String',
          attributeName: 'role',
          type: 'attribute'
        }, {
          name: 'arcrole',
          typeInfo: 'String',
          attributeName: 'arcrole',
          type: 'attribute'
        }, {
          name: 'title',
          typeInfo: 'String',
          attributeName: 'title',
          type: 'attribute'
        }, {
          name: 'show',
          typeInfo: 'String',
          attributeName: 'show',
          type: 'attribute'
        }, {
          name: 'actuate',
          typeInfo: 'String',
          attributeName: 'actuate',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'DomainMetadataType',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'reference',
          typeInfo: 'String',
          attributeName: {
            localPart: 'reference',
            namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ValueType',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }]
    }, {
      type: 'classInfo',
      localName: 'ManifestType',
      baseTypeInfo: 'OWS.BasicIdentificationType',
      propertyInfos: [{
          type: 'element',
          name: 'referenceGroup',
          collection: true,
          elementName: 'ReferenceGroup',
          typeInfo: 'OWS.ReferenceGroupType'
        }]
    }, {
      type: 'classInfo',
      localName: 'OperationsMetadata',
      propertyInfos: [{
          type: 'element',
          name: 'operation',
          collection: true,
          elementName: 'Operation',
          typeInfo: 'OWS.Operation'
        }, {
          type: 'element',
          name: 'parameter',
          collection: true,
          elementName: 'Parameter',
          typeInfo: 'OWS.DomainType'
        }, {
          type: 'element',
          name: 'constraint',
          collection: true,
          elementName: 'Constraint',
          typeInfo: 'OWS.DomainType'
        }, {
          type: 'element',
          name: 'extendedCapabilities',
          elementName: 'ExtendedCapabilities',
          typeInfo: 'AnyType'
        }]
    }, {
      type: 'classInfo',
      localName: 'KeywordsType',
      propertyInfos: [{
          type: 'element',
          name: 'keyword',
          collection: true,
          elementName: 'Keyword',
          typeInfo: 'OWS.LanguageStringType'
        }, {
          type: 'element',
          name: 'type',
          elementName: 'Type',
          typeInfo: 'OWS.CodeType'
        }]
    }, {
      type: 'classInfo',
      localName: 'ResponsiblePartyType',
      propertyInfos: [{
          type: 'element',
          name: 'individualName',
          elementName: 'IndividualName',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'organisationName',
          elementName: 'OrganisationName',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'positionName',
          elementName: 'PositionName',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactInfo',
          elementName: 'ContactInfo',
          typeInfo: 'OWS.ContactType'
        }, {
          type: 'element',
          name: 'role',
          elementName: 'Role',
          typeInfo: 'OWS.CodeType'
        }]
    }, {
      type: 'classInfo',
      localName: 'AllowedValues',
      propertyInfos: [{
          name: 'valueOrRange',
          collection: true,
          elementTypeInfos: [{
              elementName: 'Range',
              typeInfo: 'OWS.RangeType'
            }, {
              elementName: 'Value',
              typeInfo: 'OWS.ValueType'
            }],
          type: 'elements'
        }]
    }, {
      type: 'classInfo',
      localName: 'RangeType',
      propertyInfos: [{
          type: 'element',
          name: 'minimumValue',
          elementName: 'MinimumValue',
          typeInfo: 'OWS.ValueType'
        }, {
          type: 'element',
          name: 'maximumValue',
          elementName: 'MaximumValue',
          typeInfo: 'OWS.ValueType'
        }, {
          type: 'element',
          name: 'spacing',
          elementName: 'Spacing',
          typeInfo: 'OWS.ValueType'
        }, {
          name: 'rangeClosure',
          typeInfo: {
            type: 'list',
            typeInfo: 'String'
          },
          attributeName: {
            localPart: 'rangeClosure',
            namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ExceptionReport',
      propertyInfos: [{
          type: 'element',
          name: 'exception',
          collection: true,
          elementName: 'Exception',
          typeInfo: 'OWS.ExceptionType'
        }, {
          name: 'version',
          typeInfo: 'String',
          attributeName: {
            localPart: 'version'
          },
          type: 'attribute'
        }, {
          name: 'lang',
          typeInfo: 'String',
          attributeName: {
            localPart: 'lang',
            namespaceURI: 'http:\/\/www.w3.org\/XML\/1998\/namespace'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ExceptionType',
      propertyInfos: [{
          type: 'element',
          name: 'exceptionText',
          collection: true,
          elementName: 'ExceptionText',
          typeInfo: 'String'
        }, {
          name: 'exceptionCode',
          typeInfo: 'String',
          attributeName: {
            localPart: 'exceptionCode'
          },
          type: 'attribute'
        }, {
          name: 'locator',
          typeInfo: 'String',
          attributeName: {
            localPart: 'locator'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'AnyValue',
      propertyInfos: []
    }, {
      type: 'classInfo',
      localName: 'BoundingBoxType',
      propertyInfos: [{
          type: 'element',
          name: 'lowerCorner',
          elementName: 'LowerCorner',
          typeInfo: {
            type: 'list',
            typeInfo: 'Double'
          }
        }, {
          type: 'element',
          name: 'upperCorner',
          elementName: 'UpperCorner',
          typeInfo: {
            type: 'list',
            typeInfo: 'Double'
          }
        }, {
          name: 'crs',
          typeInfo: 'String',
          attributeName: {
            localPart: 'crs'
          },
          type: 'attribute'
        }, {
          name: 'dimensions',
          typeInfo: 'Integer',
          attributeName: {
            localPart: 'dimensions'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ContactType',
      propertyInfos: [{
          type: 'element',
          name: 'phone',
          elementName: 'Phone',
          typeInfo: 'OWS.TelephoneType'
        }, {
          type: 'element',
          name: 'address',
          elementName: 'Address',
          typeInfo: 'OWS.AddressType'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'OWS.OnlineResourceType'
        }, {
          type: 'element',
          name: 'hoursOfService',
          elementName: 'HoursOfService',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactInstructions',
          elementName: 'ContactInstructions',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'ReferenceType',
      baseTypeInfo: 'OWS.AbstractReferenceBaseType',
      propertyInfos: [{
          type: 'element',
          name: 'identifier',
          elementName: 'Identifier',
          typeInfo: 'OWS.CodeType'
        }, {
          type: 'element',
          name: '_abstract',
          collection: true,
          elementName: 'Abstract',
          typeInfo: 'OWS.LanguageStringType'
        }, {
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'metadata',
          collection: true,
          elementName: 'Metadata',
          typeInfo: 'OWS.MetadataType'
        }]
    }, {
      type: 'classInfo',
      localName: 'AbstractReferenceBaseType',
      propertyInfos: [{
          name: 'type',
          typeInfo: 'String',
          attributeName: {
            localPart: 'type',
            namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
          },
          type: 'attribute'
        }, {
          name: 'href',
          typeInfo: 'String',
          attributeName: 'href',
          type: 'attribute'
        }, {
          name: 'role',
          typeInfo: 'String',
          attributeName: 'role',
          type: 'attribute'
        }, {
          name: 'arcrole',
          typeInfo: 'String',
          attributeName: 'arcrole',
          type: 'attribute'
        }, {
          name: 'title',
          typeInfo: 'String',
          attributeName: 'title',
          type: 'attribute'
        }, {
          name: 'show',
          typeInfo: 'String',
          attributeName: 'show',
          type: 'attribute'
        }, {
          name: 'actuate',
          typeInfo: 'String',
          attributeName: 'actuate',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ServiceProvider',
      propertyInfos: [{
          type: 'element',
          name: 'providerName',
          elementName: 'ProviderName',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'providerSite',
          elementName: 'ProviderSite',
          typeInfo: 'OWS.OnlineResourceType'
        }, {
          type: 'element',
          name: 'serviceContact',
          elementName: 'ServiceContact',
          typeInfo: 'OWS.ResponsiblePartySubsetType'
        }]
    }, {
      type: 'classInfo',
      localName: 'OnlineResourceType',
      propertyInfos: [{
          name: 'type',
          typeInfo: 'String',
          attributeName: 'type',
          type: 'attribute'
        }, {
          name: 'href',
          typeInfo: 'String',
          attributeName: 'href',
          type: 'attribute'
        }, {
          name: 'role',
          typeInfo: 'String',
          attributeName: 'role',
          type: 'attribute'
        }, {
          name: 'arcrole',
          typeInfo: 'String',
          attributeName: 'arcrole',
          type: 'attribute'
        }, {
          name: 'title',
          typeInfo: 'String',
          attributeName: 'title',
          type: 'attribute'
        }, {
          name: 'show',
          typeInfo: 'String',
          attributeName: 'show',
          type: 'attribute'
        }, {
          name: 'actuate',
          typeInfo: 'String',
          attributeName: 'actuate',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ResponsiblePartySubsetType',
      propertyInfos: [{
          type: 'element',
          name: 'individualName',
          elementName: 'IndividualName',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'positionName',
          elementName: 'PositionName',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactInfo',
          elementName: 'ContactInfo',
          typeInfo: 'OWS.ContactType'
        }, {
          type: 'element',
          name: 'role',
          elementName: 'Role',
          typeInfo: 'OWS.CodeType'
        }]
    }, {
      type: 'classInfo',
      localName: 'GetCapabilitiesType',
      propertyInfos: [{
          type: 'element',
          name: 'acceptVersions',
          elementName: 'AcceptVersions',
          typeInfo: 'OWS.AcceptVersionsType'
        }, {
          type: 'element',
          name: 'sections',
          elementName: 'Sections',
          typeInfo: 'OWS.SectionsType'
        }, {
          type: 'element',
          name: 'acceptFormats',
          elementName: 'AcceptFormats',
          typeInfo: 'OWS.AcceptFormatsType'
        }, {
          name: 'updateSequence',
          typeInfo: 'String',
          attributeName: {
            localPart: 'updateSequence'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ReferenceGroupType',
      baseTypeInfo: 'OWS.BasicIdentificationType',
      propertyInfos: [{
          name: 'abstractReferenceBase',
          collection: true,
          elementName: 'AbstractReferenceBase',
          typeInfo: 'OWS.AbstractReferenceBaseType',
          type: 'elementRef'
        }]
    }, {
      type: 'classInfo',
      localName: 'ServiceReferenceType',
      baseTypeInfo: 'OWS.ReferenceType',
      propertyInfos: [{
          type: 'element',
          name: 'requestMessage',
          elementName: 'RequestMessage',
          typeInfo: 'AnyType'
        }, {
          type: 'element',
          name: 'requestMessageReference',
          elementName: 'RequestMessageReference',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'GetResourceByIdType',
      propertyInfos: [{
          type: 'element',
          name: 'resourceID',
          collection: true,
          elementName: 'ResourceID',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'outputFormat',
          elementName: 'OutputFormat',
          typeInfo: 'String'
        }, {
          name: 'service',
          typeInfo: 'String',
          attributeName: {
            localPart: 'service'
          },
          type: 'attribute'
        }, {
          name: 'version',
          typeInfo: 'String',
          attributeName: {
            localPart: 'version'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ServiceIdentification',
      baseTypeInfo: 'OWS.DescriptionType',
      propertyInfos: [{
          type: 'element',
          name: 'serviceType',
          elementName: 'ServiceType',
          typeInfo: 'OWS.CodeType'
        }, {
          type: 'element',
          name: 'serviceTypeVersion',
          collection: true,
          elementName: 'ServiceTypeVersion',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'profile',
          collection: true,
          elementName: 'Profile',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'fees',
          elementName: 'Fees',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'accessConstraints',
          collection: true,
          elementName: 'AccessConstraints',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'DescriptionType',
      propertyInfos: [{
          type: 'element',
          name: 'title',
          collection: true,
          elementName: 'Title',
          typeInfo: 'OWS.LanguageStringType'
        }, {
          type: 'element',
          name: '_abstract',
          collection: true,
          elementName: 'Abstract',
          typeInfo: 'OWS.LanguageStringType'
        }, {
          type: 'element',
          name: 'keywords',
          collection: true,
          elementName: 'Keywords',
          typeInfo: 'OWS.KeywordsType'
        }]
    }, {
      type: 'classInfo',
      localName: 'LanguageStringType',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'lang',
          typeInfo: 'String',
          attributeName: {
            localPart: 'lang',
            namespaceURI: 'http:\/\/www.w3.org\/XML\/1998\/namespace'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ValuesReference',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'reference',
          typeInfo: 'String',
          attributeName: {
            localPart: 'reference',
            namespaceURI: 'http:\/\/www.opengis.net\/ows\/1.1'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'NoValues',
      propertyInfos: []
    }, {
      type: 'classInfo',
      localName: 'WGS84BoundingBoxType',
      baseTypeInfo: 'OWS.BoundingBoxType',
      propertyInfos: []
    }, {
      type: 'classInfo',
      localName: 'AcceptFormatsType',
      propertyInfos: [{
          type: 'element',
          name: 'outputFormat',
          collection: true,
          elementName: 'OutputFormat',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'UnNamedDomainType',
      propertyInfos: [{
          type: 'element',
          name: 'allowedValues',
          elementName: 'AllowedValues',
          typeInfo: 'OWS.AllowedValues'
        }, {
          type: 'element',
          name: 'anyValue',
          elementName: 'AnyValue',
          typeInfo: 'OWS.AnyValue'
        }, {
          type: 'element',
          name: 'noValues',
          elementName: 'NoValues',
          typeInfo: 'OWS.NoValues'
        }, {
          type: 'element',
          name: 'valuesReference',
          elementName: 'ValuesReference',
          typeInfo: 'OWS.ValuesReference'
        }, {
          type: 'element',
          name: 'defaultValue',
          elementName: 'DefaultValue',
          typeInfo: 'OWS.ValueType'
        }, {
          type: 'element',
          name: 'meaning',
          elementName: 'Meaning',
          typeInfo: 'OWS.DomainMetadataType'
        }, {
          type: 'element',
          name: 'dataType',
          elementName: 'DataType',
          typeInfo: 'OWS.DomainMetadataType'
        }, {
          type: 'element',
          name: 'uom',
          elementName: 'UOM',
          typeInfo: 'OWS.DomainMetadataType'
        }, {
          type: 'element',
          name: 'referenceSystem',
          elementName: 'ReferenceSystem',
          typeInfo: 'OWS.DomainMetadataType'
        }, {
          type: 'element',
          name: 'metadata',
          collection: true,
          elementName: 'Metadata',
          typeInfo: 'OWS.MetadataType'
        }]
    }, {
      type: 'classInfo',
      localName: 'SectionsType',
      propertyInfos: [{
          type: 'element',
          name: 'section',
          collection: true,
          elementName: 'Section',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'ContentsBaseType',
      propertyInfos: [{
          type: 'element',
          name: 'datasetDescriptionSummary',
          collection: true,
          elementName: 'DatasetDescriptionSummary',
          typeInfo: 'OWS.DatasetDescriptionSummaryBaseType'
        }, {
          type: 'element',
          name: 'otherSource',
          collection: true,
          elementName: 'OtherSource',
          typeInfo: 'OWS.MetadataType'
        }]
    }, {
      type: 'classInfo',
      localName: 'TelephoneType',
      propertyInfos: [{
          type: 'element',
          name: 'voice',
          collection: true,
          elementName: 'Voice',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'facsimile',
          collection: true,
          elementName: 'Facsimile',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'BasicIdentificationType',
      baseTypeInfo: 'OWS.DescriptionType',
      propertyInfos: [{
          type: 'element',
          name: 'identifier',
          elementName: 'Identifier',
          typeInfo: 'OWS.CodeType'
        }, {
          type: 'element',
          name: 'metadata',
          collection: true,
          elementName: 'Metadata',
          typeInfo: 'OWS.MetadataType'
        }]
    }, {
      type: 'classInfo',
      localName: 'IdentificationType',
      baseTypeInfo: 'OWS.BasicIdentificationType',
      propertyInfos: [{
          name: 'boundingBox',
          collection: true,
          elementName: 'BoundingBox',
          typeInfo: 'OWS.BoundingBoxType',
          type: 'elementRef'
        }, {
          type: 'element',
          name: 'outputFormat',
          collection: true,
          elementName: 'OutputFormat',
          typeInfo: 'String'
        }, {
          name: 'availableCRS',
          collection: true,
          elementName: 'AvailableCRS',
          typeInfo: 'String',
          type: 'elementRef'
        }]
    }, {
      type: 'classInfo',
      localName: 'AddressType',
      propertyInfos: [{
          type: 'element',
          name: 'deliveryPoint',
          collection: true,
          elementName: 'DeliveryPoint',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'city',
          elementName: 'City',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'administrativeArea',
          elementName: 'AdministrativeArea',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'postalCode',
          elementName: 'PostalCode',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'country',
          elementName: 'Country',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'electronicMailAddress',
          collection: true,
          elementName: 'ElectronicMailAddress',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'CapabilitiesBaseType',
      propertyInfos: [{
          type: 'element',
          name: 'serviceIdentification',
          elementName: 'ServiceIdentification',
          typeInfo: 'OWS.ServiceIdentification'
        }, {
          type: 'element',
          name: 'serviceProvider',
          elementName: 'ServiceProvider',
          typeInfo: 'OWS.ServiceProvider'
        }, {
          type: 'element',
          name: 'operationsMetadata',
          elementName: 'OperationsMetadata',
          typeInfo: 'OWS.OperationsMetadata'
        }, {
          name: 'version',
          typeInfo: 'String',
          attributeName: {
            localPart: 'version'
          },
          type: 'attribute'
        }, {
          name: 'updateSequence',
          typeInfo: 'String',
          attributeName: {
            localPart: 'updateSequence'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      elementName: 'Operation',
      typeInfo: 'OWS.Operation'
    }, {
      elementName: 'DCP',
      typeInfo: 'OWS.DCP'
    }, {
      elementName: 'HTTP',
      typeInfo: 'OWS.HTTP'
    }, {
      elementName: 'OperationsMetadata',
      typeInfo: 'OWS.OperationsMetadata'
    }, {
      elementName: 'AllowedValues',
      typeInfo: 'OWS.AllowedValues'
    }, {
      elementName: 'ExceptionReport',
      typeInfo: 'OWS.ExceptionReport'
    }, {
      elementName: 'AnyValue',
      typeInfo: 'OWS.AnyValue'
    }, {
      elementName: 'ServiceProvider',
      typeInfo: 'OWS.ServiceProvider'
    }, {
      elementName: 'ServiceIdentification',
      typeInfo: 'OWS.ServiceIdentification'
    }, {
      elementName: 'ValuesReference',
      typeInfo: 'OWS.ValuesReference'
    }, {
      elementName: 'NoValues',
      typeInfo: 'OWS.NoValues'
    }, {
      elementName: 'OperationResponse',
      typeInfo: 'OWS.ManifestType'
    }, {
      elementName: 'Abstract',
      typeInfo: 'OWS.LanguageStringType'
    }, {
      elementName: 'AbstractReferenceBase',
      typeInfo: 'OWS.AbstractReferenceBaseType'
    }, {
      elementName: 'AvailableCRS',
      typeInfo: 'String'
    }, {
      elementName: 'WGS84BoundingBox',
      typeInfo: 'OWS.WGS84BoundingBoxType',
      substitutionHead: 'BoundingBox'
    }, {
      elementName: 'Metadata',
      typeInfo: 'OWS.MetadataType'
    }, {
      elementName: 'Language',
      typeInfo: 'String'
    }, {
      elementName: 'Reference',
      typeInfo: 'OWS.ReferenceType',
      substitutionHead: 'AbstractReferenceBase'
    }, {
      elementName: 'Role',
      typeInfo: 'OWS.CodeType'
    }, {
      elementName: 'UOM',
      typeInfo: 'OWS.DomainMetadataType'
    }, {
      elementName: 'ContactInfo',
      typeInfo: 'OWS.ContactType'
    }, {
      elementName: 'IndividualName',
      typeInfo: 'String'
    }, {
      elementName: 'BoundingBox',
      typeInfo: 'OWS.BoundingBoxType'
    }, {
      elementName: 'MaximumValue',
      typeInfo: 'OWS.ValueType'
    }, {
      elementName: 'ExtendedCapabilities',
      typeInfo: 'AnyType'
    }, {
      elementName: 'SupportedCRS',
      typeInfo: 'String',
      substitutionHead: 'AvailableCRS'
    }, {
      elementName: 'Title',
      typeInfo: 'OWS.LanguageStringType'
    }, {
      elementName: 'Spacing',
      typeInfo: 'OWS.ValueType'
    }, {
      elementName: 'GetResourceByID',
      typeInfo: 'OWS.GetResourceByIdType'
    }, {
      elementName: 'ServiceReference',
      typeInfo: 'OWS.ServiceReferenceType',
      substitutionHead: 'Reference'
    }, {
      elementName: 'ReferenceGroup',
      typeInfo: 'OWS.ReferenceGroupType'
    }, {
      elementName: 'GetCapabilities',
      typeInfo: 'OWS.GetCapabilitiesType'
    }, {
      elementName: 'OtherSource',
      typeInfo: 'OWS.MetadataType'
    }, {
      elementName: 'Resource',
      typeInfo: 'AnyType'
    }, {
      elementName: 'AccessConstraints',
      typeInfo: 'String'
    }, {
      elementName: 'Value',
      typeInfo: 'OWS.ValueType'
    }, {
      elementName: 'Range',
      typeInfo: 'OWS.RangeType'
    }, {
      elementName: 'PositionName',
      typeInfo: 'String'
    }, {
      elementName: 'PointOfContact',
      typeInfo: 'OWS.ResponsiblePartyType'
    }, {
      elementName: 'Keywords',
      typeInfo: 'OWS.KeywordsType'
    }, {
      elementName: 'MinimumValue',
      typeInfo: 'OWS.ValueType'
    }, {
      elementName: 'Identifier',
      typeInfo: 'OWS.CodeType'
    }, {
      elementName: 'Meaning',
      typeInfo: 'OWS.DomainMetadataType'
    }, {
      elementName: 'Manifest',
      typeInfo: 'OWS.ManifestType'
    }, {
      elementName: 'Fees',
      typeInfo: 'String'
    }, {
      elementName: 'InputData',
      typeInfo: 'OWS.ManifestType'
    }, {
      elementName: 'DefaultValue',
      typeInfo: 'OWS.ValueType'
    }, {
      elementName: 'OutputFormat',
      typeInfo: 'String'
    }, {
      elementName: 'OrganisationName',
      typeInfo: 'String'
    }, {
      elementName: 'DataType',
      typeInfo: 'OWS.DomainMetadataType'
    }, {
      elementName: 'DatasetDescriptionSummary',
      typeInfo: 'OWS.DatasetDescriptionSummaryBaseType'
    }, {
      elementName: 'AbstractMetaData',
      typeInfo: 'AnyType'
    }, {
      elementName: 'Exception',
      typeInfo: 'OWS.ExceptionType'
    }, {
      elementName: 'ReferenceSystem',
      typeInfo: 'OWS.DomainMetadataType'
    }, {
      elementName: 'Get',
      typeInfo: 'OWS.RequestMethodType',
      scope: 'OWS.HTTP'
    }, {
      elementName: 'Post',
      typeInfo: 'OWS.RequestMethodType',
      scope: 'OWS.HTTP'
    }]
};
if (typeof require === 'function') {
  module.exports.OWS = OWS;
}